### ISSUE TITLE
Popup Screenshots

### ISSUE THREAD

**Issue by StefanMenze** [conterra/mapapps-screenshot#1]
In different cases layer attributes must also be saved and printed. It would be helpful if there was an additional option to save the clicked popup as a screenshot by using this bundle

**Comment by matthiasstein** [comment]
This is not possible with the current approach, because the used [takeScreenshot](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#takeScreenshot)-method of the ArcGIS API for Javascript only allows a screenshot of the map.

> Screenshots include only elements that are rendered on the canvas (all geographical elements), but excludes overlayed DOM elements (UI, popups, measurement labels, etc.).

**Comment by matthiasstein** [comment]
Will be added via a new bundle.
