### ISSUE TITLE
not compatible with mapapps 4.14

### ISSUE THREAD

**Issue by kbor-maschmi** [conterra/mapapps-screenshot#3]
In mapapps 4.14 after setting an extent it cannot be cleared. Further after setting an extent the screenshot-configuration toolwindow cannot be closed.

**Comment by sholtkamp** [comment]
This issue could be replicated. 
The visual representation of a set extent is not removed on removing the extent.
However removing the extent still works in regards to the produced screenshot.

**Comment by sholtkamp** [comment]
Fixed in Version 1.1.2
